POST http://localhost:3001/review/newReview/26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkYW50ZS5ua2FkZGFyaWFuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiZmFlNWE4NDA4OGI4ZTIzODM2NjNhMGM2NDVlMmM2YzU5ODM1Nzg1OCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzA2OTI4NzYsImV4cCI6MTY3MzI4NDg3Nn0.gXncfygpDY_AG3WPL-xPLs1ptLfMNV4377kiBs2ac60

{
    "calification": 5,
    "comment": "a good product"
}