POST http://localhost:3001/user/newUser
Content-Type: application/json

{
  "first_name": "Dante",
  "last_name": "Kaddarian",
  "email":"blink.0068@gmail.com",
  "password": "11111",
  "phoneNumber": "1134965291",
  "address": "Calle Falsa 123",
  "profileImage": "https://ca.slack-edge.com/TPRS7H4PN-U03T82CPFME-cc81c7b5ab10-512",
	"isAdmin": false
}