POST http://localhost:3001/review/newReview/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkYW50ZS5ua2FkZGFyaWFuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTExMTEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjcwNTQ1OTU1LCJleHAiOjE2NzMxMzc5NTV9.QieUl7in07WAY-F1A5WbPMdZEiIbu-E3am2hLOg7KY4

{
    "calification": 5,
    "comment": "a good product"
}