const products = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/1/1.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 899,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/2/1.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/3/1.jpg",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/4/1.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/5/1.jpg",
  },
  {
    id: 6,
    title: "MacBook Pro",
    price: 1749,
    stock: 83,
    brand: "APPle",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: "https://i.dummyjson.com/data/products/6/1.png",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",

    price: 1499,

    stock: 50,
    brand: "Samsung",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",

    price: 1499,

    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/8/1.jpg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
      "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    ],
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    price: 1099,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/9/1.jpg",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    price: 1099,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    images: "https://i.dummyjson.com/data/products/10/1.jpg",
  },
  {
    id: 11,
    title: "perfume Oil",
    price: 13,
    stock: 65,
    brand: "Impression of Acqua Di Gio",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/11/1.jpg",
  },
  {
    id: 12,
    title: "Brown Perfume",
    price: 40,
    stock: 52,
    brand: "Royal_Mirage",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/12/1.jpg",
  },
  {
    id: 13,
    title: "Fog Scent Xpressio Perfume",
    price: 13,

    stock: 61,
    brand: "Fog Scent Xpressio",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    images: "https://i.dummyjson.com/data/products/13/1.jpg",
  },
  {
    id: 14,
    title: "Non-Alcoholic Concentrated Perfume Oil",
    price: 120,
    stock: 114,
    brand: "Al Munakh",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/14/1.jpg",
  },
  {
    id: 15,
    title: "Eau De Perfume Spray",
    price: 30,
    stock: 105,
    brand: "Lord - Al-Rehab",
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/15/1.jpg",
  },
  {
    id: 16,
    title: "Hyaluronic Acid Serum",
    price: 19,
    stock: 110,
    brand: "L'Oreal Paris",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/16/1.png",
  },
  {
    id: 17,
    title: "Tree Oil 30ml",
    price: 12,
    stock: 78,
    brand: "Hemani Tea",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/17/1.jpg",
  },
  {
    id: 18,
    title: "Oil Free Moisturizer 100ml",
    price: 40,
    stock: 88,
    brand: "Dermive",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/18/1.jpg",
  },
  {
    id: 19,
    title: "Skin Beauty Serum.",
    price: 46,
    stock: 54,
    brand: "ROREC White Rice",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/19/1.jpg",
  },
  {
    id: 20,
    title: "Freckle Treatment Cream- 15gm",
    price: 70,
    stock: 140,
    brand: "Fair & Clear",
    category: "skincare",
    thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/20/1.jpg",
  },
  {
    id: 21,
    title: "- Daal Masoor 500 grams",
    price: 20,
    stock: 133,
    brand: "Saaf & Khaas",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.png",
    images: "https://i.dummyjson.com/data/products/21/1.png",
  },
  {
    id: 22,
    title: "Elbow Macaroni - 400 gm",
    price: 14,
    stock: 146,
    brand: "Bake Parlor Big",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/22/1.jpg",
  },
  {
    id: 23,
    title: "Orange Essence Food Flavou",
    price: 14,
    stock: 26,
    brand: "Baking Food Items",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/23/1.jpg",
  },
  {
    id: 24,
    title: "cereals muesli fruit nuts",
    price: 46,
    stock: 113,
    brand: "fauji",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/24/1.jpg",
  },
  {
    id: 25,
    title: "Gulab Powder 50 Gram",
    price: 70,
    stock: 47,
    brand: "Dry Rose",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/25/1.png",
  },
  {
    id: 26,
    title: "Plant Hanger For Home",
    price: 41,
    stock: 131,
    brand: "Boho Decor",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/26/1.jpg",
  },
  {
    id: 27,
    title: "Flying Wooden Bird",
    price: 51,
    stock: 17,
    brand: "Flying Wooden",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    images: "https://i.dummyjson.com/data/products/27/1.jpg",
  },
  {
    id: 28,
    title: "3D Embellishment Art Lamp",
    price: 20,
    stock: 54,
    brand: "LED Lights",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/28/1.jpg",
  },
  {
    id: 29,
    title: "Handcraft Chinese style",
    price: 60,
    stock: 7,
    brand: "luxury palace",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    images: "https://i.dummyjson.com/data/products/29/1.jpg",
  },
  {
    id: 30,
    title: "Key Holder",
    price: 30,
    stock: 54,
    brand: "Golden",
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/30/1.jpg",
  },
];
module.exports = products;
