const products = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/1/1.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 899,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/2/1.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/3/1.jpg",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/4/1.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: "https://i.dummyjson.com/data/products/5/1.jpg",
  },
];

module.exports = products;
